name: macOS build
on: [workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: python -m pip install --upgrade pip PySide6 PyYAML pyinstaller
      - run: pyinstaller --name "Config Comparator" --windowed --onefile --hidden-import=yaml --collect-submodules PySide6 --collect-data PySide6 app.py
      - uses: actions/upload-artifact@v4
        with:
          name: Config-Comparator-macOS
          path: dist/**
